version: "3"
services:
  front:
    build: ./projects/graphql-code-generator-sample-frontend/
    command: yarn start
    ports:
      - "$FRONTEND_SERVER_PORT:3000"
    volumes:
      - ./projects/graphql-code-generator-sample-frontend/:/myapp/frontend
      - modules:/graphql-code-generator-sample/modules
    stdin_open: true
  back:
    build: ./projects/graphql-code-generator-sample-backend/
    command: >
      sh -c "rm -f tmp/pids/server.pid &&
      bundle exec rails server -b 0.0.0.0"
    volumes:
      - ./projects/graphql-code-generator-sample-backend/:/myapp/backend
      - bundle:/graphql-code-generator-sample/bundle
    ports:
      - "$BACKEND_SERVER_PORT:3000"
    environment:
      - BUNDLE_PATH=/graphql-code-generator-sample/bundle
    depends_on:
      - postgres
    tty: true
    stdin_open: true
  postgres:
    image: postgres:9.6-alpine
    volumes:
      - postgresql-data:/var/lib/postgresql
    ports:
      - "$DATABASE_PORT:5432"
    environment:
      - POSTGRES_USER=$DATABASE_USERNAME
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - LC_COLLATE=C
      - LC_CTYPE=C
      - LC_MESSAGES=C
      - LC_MONETARY=C
      - LC_NUMERIC=C
      - LC_TIME=C
volumes:
  modules:
  bundle:
  postgresql-data:
